### ISSUE TITLE
Exception while getting /openapi.json

### ISSUE THREAD

**Issue by dardoguidobono** [atompie/tracardi#50]
172.18.0.1:39336 - "GET /docs HTTP/1.0" 200
172.18.0.1:39340 - "GET /openapi.json HTTP/1.0" 500
[2021-08-09 22:52:20 +0000] [9] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/local/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 410, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 58, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 107, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'getset_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

**Comment by dardoguidobono** [comment]
using docker version tracardi/tracardi:0.5.0.rc-1

**Comment by atompie** [comment]
This error was solved - I see if I created a docker from the right version.

**Comment by atompie** [comment]
Please pull docker image again it is fixed.
